<a href="https://colab.research.google.com/github/sarmuh/Bank-Customer-Churn-ML/blob/main/CUSTOMER_CHURN_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

import sklearn


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.linear_model import LogisticRegression,RidgeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.dummy import DummyClassifier


from sklearn.metrics import classification_report,f1_score,confusion_matrix

In [114]:
df = pd.read_csv("/content/BANK_CUSTOMER_CHURN")
df.sample(5)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
9273,616,1,31,1,0.00,2,1,1,54706.75,0,1,0,0
2768,669,1,26,4,0.00,2,1,1,197594.34,0,1,0,0
8156,434,1,71,9,119496.87,1,1,0,125848.88,0,0,1,0
4741,651,1,45,2,165901.59,2,1,0,23054.51,1,1,0,0
9971,833,0,34,3,144751.81,1,0,0,166472.81,0,1,0,0

In [115]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [116]:
df_over = pd.concat([df[df['Exited']==1], df[df['Exited']==0].sample(n=2040, random_state=11)])
df_over['Exited'].value_counts()

Exited
0    2040
1    2037
Name: count, dtype: int64

In [117]:
X = df_over.drop('Exited',axis=1)
y = df_over['Exited']
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=11,stratify=y)

In [118]:
#RandomForestClassifier
modelRF = RandomForestClassifier(n_estimators=500,random_state=11,n_jobs=-1)
modelRF.fit(X_train,y_train)
y_pred = modelRF.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[325  83]
 [105 303]]
              precision    recall  f1-score   support

           0       0.76      0.80      0.78       408
           1       0.78      0.74      0.76       408

    accuracy                           0.77       816
   macro avg       0.77      0.77      0.77       816
weighted avg       0.77      0.77      0.77       816

In [119]:
#DecisionTreetClassifier
modelDT = DecisionTreeClassifier()
modelDT.fit(X_train,y_train)
y_pred = modelDT.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[291 117]
 [125 283]]
              precision    recall  f1-score   support

           0       0.70      0.71      0.71       408
           1       0.71      0.69      0.70       408

    accuracy                           0.70       816
   macro avg       0.70      0.70      0.70       816
weighted avg       0.70      0.70      0.70       816

In [120]:
#XGBClassifier
modelXGB = XGBClassifier()
modelXGB.fit(X_train,y_train)
y_pred = modelXGB.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[326  82]
 [115 293]]
              precision    recall  f1-score   support

           0       0.74      0.80      0.77       408
           1       0.78      0.72      0.75       408

    accuracy                           0.76       816
   macro avg       0.76      0.76      0.76       816
weighted avg       0.76      0.76      0.76       816

In [121]:
#CatBoostClassifie
modelCB = CatBoostClassifier(iterations=700,verbose=0)
modelCB.fit(X_train,y_train)
y_pred = modelCB.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[333  75]
 [ 92 316]]
              precision    recall  f1-score   support

           0       0.78      0.82      0.80       408
           1       0.81      0.77      0.79       408

    accuracy                           0.80       816
   macro avg       0.80      0.80      0.80       816
weighted avg       0.80      0.80      0.80       816

In [122]:
#CatBoostClassifie
modelLGBM = LGBMClassifier(n_estimators=800)
modelLGBM.fit(X_train,y_train)
y_pred = modelLGBM.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[LightGBM] [Info] Number of positive: 1629, number of negative: 1632
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000218 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 853
[LightGBM] [Info] Number of data points in the train set: 3261, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499540 -> initscore=-0.001840
[LightGBM] [Info] Start training from score -0.001840
[[323  85]
 [108 300]]
              precision    recall  f1-score   support

           0       0.75      0.79      0.77       408
           1       0.78      0.74      0.76       408

    accuracy                           0.76       816
   macro avg       0.76      0.76      0.76       816
weighted avg       0.76      0.76      0.76       816

In [123]:
scaler = StandardScaler()
X_train[['CreditScore','Age','Balance','NumOfProducts','EstimatedSalary']] = scaler.fit_transform(X_train[['CreditScore','Age','Balance','NumOfProducts','EstimatedSalary']])
X_test[['CreditScore','Age','Balance','NumOfProducts','EstimatedSalary']] = scaler.transform(X_test[['CreditScore','Age','Balance','NumOfProducts','EstimatedSalary']])

In [124]:
#LogisticRegression
modelLR = LogisticRegression(max_iter=100)
modelLR.fit(X_train,y_train)
y_pred = modelLR.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[300 108]
 [111 297]]
              precision    recall  f1-score   support

           0       0.73      0.74      0.73       408
           1       0.73      0.73      0.73       408

    accuracy                           0.73       816
   macro avg       0.73      0.73      0.73       816
weighted avg       0.73      0.73      0.73       816

In [125]:
#KNeighborsClassifier
modelKN = KNeighborsClassifier(n_neighbors=7)
modelKN.fit(X_train,y_train)
y_pred = modelKN.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[317  91]
 [114 294]]
              precision    recall  f1-score   support

           0       0.74      0.78      0.76       408
           1       0.76      0.72      0.74       408

    accuracy                           0.75       816
   macro avg       0.75      0.75      0.75       816
weighted avg       0.75      0.75      0.75       816

In [126]:
#SVC
modelSVC = SVC()
modelSVC.fit(X_train,y_train)
y_pred = modelSVC.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[320  88]
 [102 306]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77       408
           1       0.78      0.75      0.76       408

    accuracy                           0.77       816
   macro avg       0.77      0.77      0.77       816
weighted avg       0.77      0.77      0.77       816